language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
 - pip install .
 - pip install -r requirements.txt
# command to run tests
script: python setup.py test
# To specify environment variables, use the env key. Example:
# env: PYTHONPATH=/some_path/here